data_config:
  name: mnist
  partitioning: iid
  batch_size: 16
model_cfg:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torch.nn.Flatten
    - _target_: torch.nn.Linear
      in_features: 784
      out_features: 128
    - _target_: torch.nn.ReLU
    - _target_: torch.nn.Linear
      in_features: 128
      out_features: 10
backend_config:
  num_cpus: 02
  num_gpus: 0